baseURL = "https://seppedekeyser.be"
languageCode = "en-us"
title = "Seppe Dekeyser"
copyright = "©️ 2022 - 2023 | Seppe Dekeyser"
staticDir = ["static"]

[params]
  description = "Aspiring engine and graphics programmer"

[params.Twitter]
  creator = "SeppahBaws"
  site = "SeppahBaws"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About Me"
    url = "/about-me"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "https://renderingpixels.com"
    weight = 3
  [[menu.main]]
    name = "Resume"
    url = "/resume.pdf"
    weight = 4