name: Build Hugo site and deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: Build
        run: hugo --minify
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: public
      # - if: ${{ github.event_name == 'push' }}
      #   name: Deploy via FTP
      #   uses: airvzxf/ftp-deployment-action@latest
      #   with:
      #     server: ${{ secrets.FTP_URL }}
      #     user: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local_dir: "./public"
      #     delete: false
